---

- name: VILLAS devops
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_user: vagrant
    ansible_become: true
    ansible_python_interpreter: "{{ansible_playbook_python}}"

  roles:
    - role: jpnorenam.YALUK
